version: '3.3'

services:
        sample-prod:
                container_name: course-review-client
                build:
                        context: .
                        dockerfile: Dockerfile
                volumes:
                        - '.:/app'
                        - '/app/node_modules'
                ports:
                        - 3001:3000
                environment:
                        - CHOKIDAR_USEPOLLING=true
